// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2nrP7mA2E4xDa0MigYVXf5f7Vc5aYznc',
    appId: '1:110570622418:web:366b719f62bf5e9bfc0c0b',
    messagingSenderId: '110570622418',
    projectId: 'gwo-cat-expensestracker',
    authDomain: 'gwo-cat-expensestracker.firebaseapp.com',
    storageBucket: 'gwo-cat-expensestracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIKUj_AGawZCfMy0WNxsJXb1IM_3Yq-8',
    appId: '1:110570622418:android:c4933e2eace80c1dfc0c0b',
    messagingSenderId: '110570622418',
    projectId: 'gwo-cat-expensestracker',
    storageBucket: 'gwo-cat-expensestracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCalSy-VGKfftVrp8CCQwl6Z8MeCPpFteU',
    appId: '1:110570622418:ios:326d5722810f3cd5fc0c0b',
    messagingSenderId: '110570622418',
    projectId: 'gwo-cat-expensestracker',
    storageBucket: 'gwo-cat-expensestracker.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCalSy-VGKfftVrp8CCQwl6Z8MeCPpFteU',
    appId: '1:110570622418:ios:326d5722810f3cd5fc0c0b',
    messagingSenderId: '110570622418',
    projectId: 'gwo-cat-expensestracker',
    storageBucket: 'gwo-cat-expensestracker.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2nrP7mA2E4xDa0MigYVXf5f7Vc5aYznc',
    appId: '1:110570622418:web:3177b4fc19ddebacfc0c0b',
    messagingSenderId: '110570622418',
    projectId: 'gwo-cat-expensestracker',
    authDomain: 'gwo-cat-expensestracker.firebaseapp.com',
    storageBucket: 'gwo-cat-expensestracker.firebasestorage.app',
  );
}
